# Desktop App Build
FROM node:22-alpine AS builder

WORKDIR /app

COPY desktop-app/package*.json ./
RUN npm ci

COPY desktop-app .
RUN npm run build

# Static file server
FROM node:22-alpine

WORKDIR /app

RUN npm install -g http-server

COPY --from=builder /app/dist .

EXPOSE 8000

CMD ["http-server", "-p", "8000", "-c-1"]
