<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="4.0.0" />
    <PackageReference Include="Microsoft.ML.FastTree" Version="4.0.0" />
    <ProjectReference Include="..\StockTrader.ServiceContracts\StockTrader.ServiceContracts.csproj" />
  </ItemGroup>
</Project>
