// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockTrader.Data;

#nullable disable

namespace StockTrader.Data.EfMigrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901131747_PersistPositionExecutionContext")]
    partial class PersistPositionExecutionContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("StockTrader.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("StockTrader.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("StockTrader.Models.CustomPatternDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AtrStopMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AtrTargetMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<string>("CircuitBreakerJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultAllocationPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DynamicExitJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableLiveTrading")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryGroupsLogic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryLogic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryRulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitGroupsLogic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitRulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitRulesLogic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHoldingBars")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PartialProfitR")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortfolioRulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReentryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireBullRegime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScalingRulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SizingMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeFilterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeFrame")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TrailingAtr")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseWeightTiers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeightTiersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("CustomPatterns");
                });

            modelBuilder.Entity("StockTrader.Models.FinancialAuthorityFence", b =>
                {
                    b.Property<string>("TransitionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ActivityJournalCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorityGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EnabledConsumerLag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryReconciliation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FenceHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCompletedPositionBarUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManualCommandAcceptance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewEntryAcceptance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionReconciliation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnresolvedBrokerEffectCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnresolvedIntentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("TransitionId");

                    b.HasIndex("IsReleased", "AuthorityGeneration");

                    b.ToTable("FinancialAuthorityFences");
                });

            modelBuilder.Entity("StockTrader.Models.FinancialAuthorityMirror", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorityGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MirroredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransitionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FinancialAuthorityMirror", (string)null);
                });

            modelBuilder.Entity("StockTrader.Models.FinancialImportRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("FilePath", "Fingerprint")
                        .IsUnique();

                    b.ToTable("FinancialImportRuns");
                });

            modelBuilder.Entity("StockTrader.Models.FinancialSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AsOfDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NetIncomeCurrent")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NetIncomePrevious")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OperatingIncomeCurrent")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OperatingIncomePrevious")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OperatingMarginPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PbRatio")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PeRatio")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RevenueCurrent")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RevenuePrevious")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RoePercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate");

                    b.HasIndex("Symbol");

                    b.HasIndex("Symbol", "AsOfDate")
                        .IsUnique();

                    b.ToTable("FinancialSnapshots");
                });

            modelBuilder.Entity("StockTrader.Models.OhlcvBar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeFrame")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Vwap")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "TimeFrame", "Timestamp")
                        .IsUnique();

                    b.HasIndex("TimeFrame", "Symbol", "Timestamp");

                    b.ToTable("OhlcvBars");
                });

            modelBuilder.Entity("StockTrader.Models.OptimizationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppliedResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoApplyBestResult")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoApplyMinTrades")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContinuousMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentChunkIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAutoAppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastAutoAppliedResultId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAutoApplyMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastProgressAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxDurationHours")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MaxTestedCombinations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RankBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TestedCombinations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopResultsToKeep")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCombinations")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Priority");

                    b.ToTable("OptimizationJobs");
                });

            modelBuilder.Entity("StockTrader.Models.OptimizationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualizedReturn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CalmarRatio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxDrawdown")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OosAnnualizedReturn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OosCalmarRatio")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OosMaxDrawdown")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OosProfitFactor")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OosSharpeRatio")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OosSortinoRatio")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OosTotalReturn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OosTotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OosWinRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfitFactor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SharpeRatio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SortinoRatio")
                        .HasColumnType("TEXT");

                    b.Property<long>("TestedAtCombination")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalReturn")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Rank");

                    b.ToTable("OptimizationResults");
                });

            modelBuilder.Entity("StockTrader.Models.OptimizationWorkerLeaseRecord", b =>
                {
                    b.Property<string>("LeaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthoritativeResultHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthoritativeResultJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Authority")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CancellationGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CanonicalCommittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalResultHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ComparedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComparisonDetail")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComparisonStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("LeaseGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LeasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TestedCombinations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("LeaseId");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasFilter("\"SubmissionId\" IS NOT NULL");

                    b.HasIndex("Status", "ExpiresAt", "CreatedAt");

                    b.HasIndex("JobId", "Purpose", "InputHash", "Authority")
                        .IsUnique();

                    b.ToTable("OptimizationWorkerLeases");
                });

            modelBuilder.Entity("StockTrader.Models.PatternSignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomPatternName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuperseded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatternType")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("ScoringAtrPercent")
                        .HasColumnType("REAL");

                    b.Property<float?>("ScoringBollingerPosition")
                        .HasColumnType("REAL");

                    b.Property<int?>("ScoringFeatureVersion")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("ScoringHistoricalWinRate")
                        .HasColumnType("REAL");

                    b.Property<float?>("ScoringLongTrendHistoryAvailable")
                        .HasColumnType("REAL");

                    b.Property<float?>("ScoringMarketRegimeCode")
                        .HasColumnType("REAL");

                    b.Property<float?>("ScoringPriceVsLongMovingAverage")
                        .HasColumnType("REAL");

                    b.Property<float?>("ScoringRiskRewardRatio")
                        .HasColumnType("REAL");

                    b.Property<float?>("ScoringRsi")
                        .HasColumnType("REAL");

                    b.Property<float?>("ScoringVolumeRatio")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("SignalBarAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLossPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "IsSuperseded", "DetectedAt");

                    b.HasIndex("Symbol", "PatternType", "SignalBarAt")
                        .IsUnique()
                        .HasFilter("\"CustomPatternName\" IS NULL AND \"SignalBarAt\" IS NOT NULL");

                    b.HasIndex("Symbol", "PatternType", "CustomPatternName", "SignalBarAt")
                        .IsUnique()
                        .HasFilter("\"CustomPatternName\" IS NOT NULL AND \"SignalBarAt\" IS NOT NULL");

                    b.ToTable("PatternSignals");
                });

            modelBuilder.Entity("StockTrader.Models.PatternStats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgLossPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvgWinPercent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxDrawdownPercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatternType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatternType", "Symbol")
                        .IsUnique();

                    b.ToTable("PatternStats");
                });

            modelBuilder.Entity("StockTrader.Models.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BreakevenApplied")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomPatternName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryAtr")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryMarketDataEvidenceJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionArtifactJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionOrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ExitOrderId");

                    b.Property<int?>("ExecutionRequestKind")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExecutionRequestMarksPartialProfit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ExitRequestMarksPartialProfit");

                    b.Property<int?>("ExecutionRequestQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ExitRequestQuantity");

                    b.Property<string>("ExecutionRequestReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("ExitRequestReason");

                    b.Property<int?>("ExecutionRequestRuleIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExecutionRequestedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ExitRequestedAt");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HighSinceEntry")
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InitialRiskDistance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastEvaluatedBarUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastEvaluatedEvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastEvaluatedMarketDataRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PartialProfitTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatternType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceSignalId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StopLossPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrailingStopActivated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClosedAt");

                    b.HasIndex("SourceSignalId");

                    b.HasIndex("Symbol");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("StockTrader.Models.PositionScalingExecution", b =>
                {
                    b.Property<long>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuleIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExecutionCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("PositionId", "RuleIndex");

                    b.ToTable("PositionScalingExecutions", (string)null);
                });

            modelBuilder.Entity("StockTrader.Models.SymbolProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BacktestFrom")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BacktestMaxDrawdown")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BacktestReturnPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BacktestSharpe")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BacktestTo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BacktestTrades")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BacktestWinRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnabledPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTotalPositions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterOverridesJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RiskPerTradePercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightStrategyJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "IsActive");

                    b.HasIndex("Symbol", "Name")
                        .IsUnique();

                    b.ToTable("SymbolProfiles");
                });

            modelBuilder.Entity("StockTrader.Models.Ticker", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MarketCap")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol");

                    b.HasIndex("Sector");

                    b.ToTable("Tickers");
                });

            modelBuilder.Entity("StockTrader.Models.TradeRecommendation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomPatternName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntryAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryExecutionNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryOrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntryRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Expectancy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuperseded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatternType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PositionSize")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShareQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceSignalId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StopLossPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasExecuted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("SourceSignalId")
                        .IsUnique()
                        .HasFilter("\"SourceSignalId\" IS NOT NULL");

                    b.HasIndex("IsSuperseded", "GeneratedAt");

                    b.HasIndex("WasExecuted", "EntryRequestedAt");

                    b.ToTable("TradeRecommendations");
                });

            modelBuilder.Entity("StockTrader.Models.TradeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomPatternName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatternType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PnL")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PnLPercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceSignalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceSignalId");

                    b.HasIndex("PatternType", "EntryTime");

                    b.ToTable("TradeRecords");
                });

            modelBuilder.Entity("StockTrader.Models.TradingAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiSecret")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("BrokerType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrokerType");

                    b.HasIndex("IsActive");

                    b.ToTable("TradingAccounts");
                });

            modelBuilder.Entity("StockTrader.Models.UserSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AccountSize")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyLossLimitPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("DailyReportTimeKst")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordWebhookUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailTo")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EnableDiscord")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("EnableEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("EnableTelegram")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnabledPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiveParameterOverridesJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPositionsPerSector")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTotalPositions")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinExpectancy")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredDataSource")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RiskPerTradePercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SmtpUseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoundAlerts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelegramBotToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramChatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tqqq200SmaAllowedSymbols")
                        .HasColumnType("TEXT");

                    b.Property<string>("WatchlistSymbols")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("StockTrader.Models.OptimizationResult", b =>
                {
                    b.HasOne("StockTrader.Models.OptimizationJob", "Job")
                        .WithMany("Results")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("StockTrader.Models.OptimizationWorkerLeaseRecord", b =>
                {
                    b.HasOne("StockTrader.Models.OptimizationJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockTrader.Models.PositionScalingExecution", b =>
                {
                    b.HasOne("StockTrader.Models.Position", "Position")
                        .WithMany("ScalingExecutions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("StockTrader.Models.OptimizationJob", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("StockTrader.Models.Position", b =>
                {
                    b.Navigation("ScalingExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
