apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: stocktrader-optimization-worker-egress
  namespace: stocktrader
spec:
  podSelector:
    matchLabels:
      app: stocktrader-optimization-worker
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: stocktrader
      podSelector:
        matchLabels:
          app: stocktrader-api
    ports:
    - protocol: TCP
      port: 5443
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
