apiVersion: v1
kind: Secret
metadata:
  name: stocktrader-alpaca
  namespace: stocktrader
type: Opaque
stringData:
  Alpaca__ApiKey: "YOUR_ALPACA_API_KEY"
  Alpaca__ApiSecret: "YOUR_ALPACA_API_SECRET"
  Alpaca__IsPaper: "true"
  Alpaca__EnableStreaming: "false"
